amharic/urls.py
from django.urls import path,re_path
from . import views

app_name = 'amharic'
urlpatterns = [
    path("",views.index,name="amharic"),
    path("about/",views.about,name="a_about"),
    path("faq/",views.faq,name="a_faq"),
]

ludis/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from amharic import views
from django.contrib.sitemaps.views import sitemap
from repair.sitemaps import StaticSitemap
from django.views.generic.base import TemplateView

sitemaps = {
    'posts':StaticSitemap
}

admin.site.name = "Ludis"
admin.site.site_header = "Ludis Administration"

urlpatterns = [
    path('admin-ludis/', admin.site.urls),
    path('',include(('repair.urls','repair'),namespace='repair')),
    path('amh/',include('amharic.urls')),
    path(
        'sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'
        ),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^ads\.txt$', views.googleadsense, name='google_adsense'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

repair/urls.py
from django.urls import path
from . import views

app_name = 'repair'

urlpatterns = [
    path("",views.index,name="index"),
    path("about/",views.about,name="about"),
    path("faq/",views.faq,name="faq"),
    path("login/",views.login_user,name="login"),
    path("terms/",views.terms,name="terms"),
    path("blog/",views.blog,name="blog"),
    path('category/<int:id>/', views.category, name='category'),
    path('category/blog-post/<int:id>/', views.post, name='post'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.custom_logout, name='logout'),
    path('admin-page/',views.admin_page, name='admin'),
    path('admin-page/about-edit',views.about_edit, name='about_edit'),
    path('admin-page/faq-edit',views.sup_edit, name='faq_edit'),
    path('admin-page/user-edit',views.user_edit, name='user_edit'),
    path('admin-page/order',views.book, name='book'),
    path('admin-page/apply',views.com, name='apply'),
    path('admin-page/new',views.new, name='new'),
    path('admin-page/blog/post',views.blogpost, name='blogpost'),
    path('admin-page/setting',views.setting, name='setting'),
    path('admin-page/blog/category',views.cat_edit, name='cat_edit'),
    path('admin-page/profile',views.admin_profile,name='admin_profile'),
    path('register/',views.register_user,name='register'),
    path('register/personal-data/',views.register_user2,name='register2'),
    path('admin-page/brand',views.brand,name='brand'),
    path('admin-page/model/<int:id>/',views.model,name='model'),
    path('admin-page/model/',views.model2,name='modelm'),
    path('admin-page/model/add/',views.modeladd,name='modeladd'),
    path('admin-page/problem/',views.problem2,name='problemm'),
    path('admin-page/problem/<int:id>/',views.problem,name='problem'),
    path('admin-page/problem/add/',views.problemadd,name='problemadd'),
    path('admin-page/price',views.price2,name='pricem'),
    path('admin-page/price/<int:id>/',views.price,name='price'),
    path('admin-page/price/add/',views.priceadd,name='priceadd'),
]

repair/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1','password2']

repair/views.py
from django.shortcuts import render,redirect
from .models import *
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .forms import *


def index(request):
    User = request.user
    brand = Brand.objects.all()
    amount = Price.objects.all()
    new = New.objects.all()
    if User.is_authenticated:
        pp = Profile.objects.get(user=User.id)
    else:
        pp = ""
    if request.method == 'POST':
        try:
            if 'no' in request.POST:
                a=request.POST['name']
                b=request.POST['email']
                c=request.POST['phone']
                d=request.POST['country']
                e=request.POST['city']
                f=request.POST['device']
                g=request.POST['model']
                h=request.POST['problem']
                i=request.POST['other']
                model=Order.objects.create(
                    name=a,
                    email=b,
                    device=f,
                    model=g,
                    problems=h,
                    others=i,
                    phone=c,
                    country=d,
                    city=e,
                    my_place=False,
                )
                if not User.is_authenticated:
                    messages.add_message(request, messages.INFO, 'Your order Placed succesfully Login with your account to become customer')
                else:
                    messages.add_message(request, messages.INFO, 'Your order Placed succesfully')
                return redirect('repair:index')
            if 'yes' in request.POST:
                a=request.POST['name']
                b=request.POST['email']
                c=request.POST['phone']
                d=request.POST['country']
                e=request.POST['city']
                f=request.POST['device']
                g=request.POST['model']
                h=request.POST['problem']
                i=request.POST['other']
                model=Order.objects.create(
                    name=a,
                    email=b,
                    device=f,
                    model=g,
                    problems=h,
                    others=i,
                    phone=c,
                    country=d,
                    city=e,
                    my_place=True,
                )
                if not User.is_authenticated:
                    messages.add_message(request, messages.INFO, 'Your order Placed succesfully Login with your account to become customer')
                else:
                    messages.add_message(request, messages.INFO, 'Your order Placed succesfully')
                return redirect('repair:index')
            if 'apply' in request.POST:
                a = request.POST['name']
                b= request.POST['email']
                c = request.POST['phone']
                d = request.FILES['file']
                e = request.POST['more']
                main = Apply.objects.create(
                    name=a,
                    email=b,
                    file=d,
                    phone=c,
                    more=e
                )
                if not User.is_authenticated:
                    messages.add_message(request, messages.INFO, 'Your personal data submitted successfully stay tuned Login with your account to become customer')
                else:
                    messages.add_message(request, messages.INFO, 'Your personal data submitted successfully stay tuned')
                return redirect('repair:index')
        except:pass
    web = Webpack.objects.get(id=1)
    context = {
        'User':User,
        'web': web,
        'pp':pp,
        'brand':brand,
        'amount':amount,
    }
    return render(request,"index.html",context)


def about(request):
    new = New.objects.all()
    web = Webpack.objects.get(id=1)
    ab = About.objects.all()
    User = request.user
    if User.is_authenticated:
        pp = Profile.objects.get(user=User.id)
    else:
        pp = ""
    context = {
        'web':web,
        'ab':ab,
        'User':User,
        'pp':pp,
        'new':new
    }
    return render(request,"about.html",context)


def faq(request):
    web = Webpack.objects.get(id=1)
    ab = Faq.objects.all()
    User = request.user
    if User.is_authenticated:
        pp = Profile.objects.get(user=User.id)
    else:
        pp = ""
    context = {
        'web':web,
        'ab':ab,
        'User':User,
        'pp':pp,
    }
    return render(request,"faq.html",context)


def login_user(request):
    web = Webpack.objects.get(id=1)
    micon = ""
    mtitle = ""
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'],password=form.cleaned_data['password'],) 
            if user is not None:
                login(request,user)
                if Profile.objects.filter(user=request.user):
                    micon = "success"
                    mtitle = "success"
                    messages.add_message(request, messages.INFO, 'Logged in Successfully now you can edit your personal information')
                    return redirect('repair:profile')
                else:
                    micon = "success"
                    mtitle = "success"
                    messages.add_message(request, messages.INFO, 'Logged in Successfully now you can add other personal information')
                    return redirect('repair:register2')
        else:
            micon = "error"
            mtitle = "error"
            messages.add_message(request, messages.INFO, 'Invalid user data entered')
    context = {
        'web':web,
        'mtitle':mtitle,
        'micon':micon,
    }
    return render(request,"login.html",context)


def terms(request):
    web = Webpack.objects.get(id=1)
    User = request.user
    context = {
        'web':web,
        'User':User,
    }
    return render(request,"terms.html",context)


def blog(request):
    web = Webpack.objects.get(id=1)
    User = request.user
    post = Post.objects.all()
    category = Category.objects.all()
    one = Post.objects.filter(level='one')
    two = Post.objects.filter(level='two')
    three = Post.objects.filter(level='three')
    four = Post.objects.filter(level='four')
    five = Post.objects.filter(level='five')
    context = {
        'web':web,
        'User':User,
        'post':post,
        'category':category,
        'one':one,
        'two':two,
        'three':three,
        'four':four,
        'five':five,
    }
    return render(request,'blog.html',context)


def category(request,id):
    category = Category.objects.get(id=id)
    web = Webpack.objects.get(id=1)
    User = request.user
    post = Post.objects.all()
    categor = Category.objects.all()
    main = Post.objects.filter(category=id)
    context = {
        'category':category,
        'web':web,
        'User':User,
        'post':post,
        'categor':categor,
        'main':main,
    }
    return render(request,'category.html',context)


def post(request,id):
    postt = Post.objects.get(id=id)
    web = Webpack.objects.get(id=1)
    User = request.user
    post = Post.objects.all()
    categor = Category.objects.all()
    context = {
        'category':category,
        'web':web,
        'User':User,
        'post':post,
        'postt':postt,
        'categor':categor,
    }
    return render(request,'post.html',context)


@login_required(login_url='login')
def profile(request):
    web = Webpack.objects.get(id=1)
    User = request.user
    micon = ""
    mtitle = ""
    history = Order.objects.filter(user=User.id)
    pp = Profile.objects.get(user=User.id)
    if request.method == 'POST':
        try:
            a = request.POST['one']
            b = request.POST['two']
            c = request.POST['three']
            d = request.POST['four']
            e = request.POST['five']
            f = request.POST['six']
            g = request.POST['seven']
            if e:
                if e == f:
                    User.set_password(e)
                    User.save()
                    micon = "success"
                    mtitle = "success"
                    messages.add_message(request, messages.INFO, 'Password Updated successfully')
                    return redirect('repair:login')
                else:
                    micon = "error"
                    mtitle = "error"
                    messages.add_message(request, messages.INFO, 'Passwords donot match please try again')
                
            User.username=c
            User.first_name=a
            User.last_name=b
            User.email=d
            User.save()
            pp.phone=g
            pp.save()
            micon = "success"
            mtitle = "success"
            messages.add_message(request, messages.INFO, 'Profile Updated successfully')      
            if request.FILES['eight']:
                h = request.FILES['eight']
                pp.profile_pic = h
                pp.save()
                micon = "success"
                mtitle = "success"
                messages.add_message(request, messages.INFO, 'Profile picture Updated successfully')  
            
        except:pass
    context = {
        'web':web,
        'User':User,
        'micon':micon,
        'mtitle':mtitle,
        'pp':pp,
        'history':history,
    }
    return render(request,'profile.html',context)



@login_required(login_url='login')
def admin_page(request):
    User = request.user
    web = Webpack.objects.get(id=1)
    cc = Apply.objects.all().count()
    a = Order.objects.all().count()
    p = Profile.objects.all().count()
    pp = Profile.objects.get(user=User.id)

repair/templates/about.html
{% extends 'base.html' %}
{% block title %}About Us{% endblock %}
{% block name %}About Us{% endblock %}
{% block main %}
<!--Featured Receipes -->
{% if new %}
<section id="news" class="bg_grey padding">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
      <h2 class="heading">What's New</h2>
      <hr class="heading_space">
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="cheffs_wrap_slider">
          <div id="news-slider" class="owl-carousel">
            {% for a in new %}
            <div class="item">
              <div class="news_content">
               <img src="{{a.image.url}}" alt="Docotor">
               <div class="comment_text">
                 <h3>{{a.name}}</h3>
                 <p>{{a.disc}}</p>
               </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endif %}


{% for a in ab %}
<section id="overview" class="padding-top">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
         <h2 class="heading">{{a.title}}</h2>
         <hr class="heading_space">
         <p>{{a.p1}}</p>
         {% if a.p2 %}
         <p>{{a.p2}}</p>
         {% endif %}
         {% if a.p3 %}
         <p>{{a.p3}}</p>
         {% endif %}
         {% if a.p4 %}
         <p>{{a.p4}}</p>
         {% endif %}
      </div>
    </div>
  </div>
</section>
{% endfor %}
{% endblock %}

repair/templates/base.html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{web.name}} | {% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="/static/css/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/bistro-icons.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/settings.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/owl.carousel.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/owl.transitions.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/jquery.fancybox.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/zerogrid.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/loader.css">
<link rel="shortcut icon" href="{{web.icon.url}}">
<link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    />
<style>
  .alertt {
    margin-top: 30px;
padding: 20px;
background-color: rgb(0, 255, 55); /* Red */
color: rgb(0, 0, 0);
margin-bottom: 15px;
}

/* The close button */
.alertt .closebtn {
margin-left: 15px;
color: rgb(0, 0, 0);
font-weight: bold;
float: right;
font-size: 22px;
line-height: 20px;
cursor: pointer;
transition: 0.3s;
}

/* When moving the mouse over the close button */
.alertt .closebtn:hover {
color: black;
}
</style>
{% block css %}{% endblock %}

<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

</head>

<body>

<!--Loader-->
<div class="loader"> 
   <div class="cssload-container">
     <div class="cssload-circle"></div>
     <div class="cssload-circle"></div>
   </div>
</div>
<!--Topbar-->
<div class="topbar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p class="pull-left hidden-xs">{{web.name}}, You break, We collect, We fix!.</p>
        <p class="pull-right"><i class="fa fa-phone"></i>contact now  {{web.phone}}</p>
      </div>
    </div>
  </div>
</div>

<!--Header-->
<header id="main-navigation">
  <div id="navigation" data-spy="affix" data-offset-top="20">
    <div class="container">
      <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-default">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#fixed-collapse-navbar" aria-expanded="false"> 
            <span class="icon-bar top-bar"></span> <span class="icon-bar middle-bar"></span> <span class="icon-bar bottom-bar"></span> 
            </button>
           <a class="navbar-brand"  href="{% url 'repair:index' %}"><img src="/static/images/logo.png" style="background: #333;padding: 10px;border-radius: 20px; width:200px;" alt="logo" class="img-responsive"></a> 
         </div>
        
            <div id="fixed-collapse-navbar" class="navbar-collapse collapse navbar-right">
              <ul class="nav navbar-nav">
                <li>
                   <a href="{% url 'repair:index'%}">Home</a>
                   
                </li>
                <li><a href="{% url 'repair:blog' %}">Blog</a></li>
                
                
                    <li><a href="{% url 'repair:about'%}">About Us</a></li>
                    <li><a href="{% url 'repair:faq' %}">FAQ</a></li>
                  
                    {% if User.is_authenticated %}
                    {% if pp.profile_pic %}
          <li><a href="{% url 'repair:profile' %}"><img  style="width: 50px;border-radius: 50%;height: 50px;" src="{{pp.profile_pic.url}}" alt=""></a></li>
          {% else %}
          <li><a href="{% url 'repair:profile' %}"><img  style="width: 50px;border-radius: 50%;height: 50px;" src="/static/images/undraw_pic_profile_re_7g2h.svg" alt=""></a></li>
          {% endif %}
                    {% else %}
                    <li><a href="{% url 'repair:login' %}">Login</a></li>
                    {% endif %}
                    <a href="{% url 'amharic:amharic' %}">
                      <img  style="width: 30px;margin-top: 10px;border-radius: 50%;height: 30px;" src="/static/images/et.jpg" alt="">
                      </a>
              </ul>
            </div>
         </nav>
         </div>
       </div>
     </div>
  </div>
</header>

<!--Page header & Title-->
<section id="page_header">
<div class="page_title">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
         <h2 class="title">{% block name %}{% endblock %}</h2>
         <p></p>
      </div>
    </div>
  </div>
</div>  
</section>
{% block main %}

{% endblock %}

<!--Footer-->
<footer class="padding-top bg_black" style="margin-top: 200px;">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6 footer_column">
        <h4 class="heading">Why {{web.name}}</h4>
        <hr class="half_space">
        <p class="half_space">We Provide Our Services To Local Customers, BILIHCARE Specializes In Its Services Without Loopholes All Your Requirements Reach Expert Hands. Our Massive Investment In Engineers, Equipment And Procedures And Consequently Will Definitely Provide You The Extreme Best Experience.</p>
      </div>
      <div class="col-md-3 col-sm-6 footer_column">
        <h4 class="heading">Quick Links</h4>
        <hr class="half_space">
        <ul class="widget_links">
          <li><a href="{% url 'repair:index' %}">Home</a></li>
          <li><a href="{% url 'repair:blog' %}">Blog</a></li>
          <li><a href="{% url 'repair:about' %}">About us</a></li>
          <li><a href="{% url 'repair:faq' %}">FAQ</a></li>
          <li><a href="{% url 'repair:terms' %}">Terms </a></li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-6 footer_column">
        <h4 class="heading">Get in Touch</h4>
        <hr class="half_space">
        <p>{{web.name}}, You break, We collect, We fix!.</p>
        <p class="address"><i class="icon-location"></i>{{web.address}}</p>
        <p class="address"><i class="fa fa-phone"></i>{{web.phone}}</p>
        <p class="address"><i class="icon-dollar"></i><a href="mailto:{{web.email}}">{{web.email}}</a></p>
      </div>  
    </div>
    <div class="row">
      <div class="col-md-12">
         <div class="copyright clearfix">
           <ul class="social_icon">
        {% if web.facebook %}
        <li><a href="{{web.facebook}}" class="facebook"><i class="fab fa-facebook-f"></i></a></li>
        {% endif %}
        {% if web.telegram %}
        <li><a href="{{web.telegram}}" class="twitter"><i class="fa fa-telegram"></i></a></li>
        {% endif %}
        {% if web.instagram %}
        <li><a href="{{web.instagram}}" class="twitter"><i class="fab fa-instagram"></i></a></li>
        {% endif %}
        {% if web.youtube %}
        <li><a href="{{web.youtube}}" class="twitter"><i class="fab fa-youtube"></i></a></li>
        {% endif %}
        {% if web.tiktok %}
        <li><a href="{{web.tiktok}}" class="twitter"><i class="fab fa-tiktok"></i></a></li>
        {% endif %}
        {% if web.email %}
        <li><a href="mailto:{{web.email}}" class="twitter"><i class="fa fa-envelope"></i></a></li>
        {% endif %}
        {% if web.twitter %}
        <li><a href="{{web.twitter}}" class="twitter"><i class="icon-twitter"></i></a></li>
        {% endif %}
               </ul>
         </div>
       </div>
     </div>
  </div>
</footer>
<a href="#" id="back-top"><i class="fa fa-angle-up fa-2x"></i></a>
{% block script %}

{% endblock %}
<script src="/static/js/js/jquery-2.2.3.js" type="text/javascript"></script>
<script src="/static/js/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/js/js/jquery.parallax-1.1.3.js"></script>
<script src="/static/js/js/jquery.appear.js"></script>  
<script src="/static/js/js/jquery-countTo.js"></script>
<script src="/static/js/js/owl.carousel.min.js" type="text/javascript"></script>
<script src="/static/js/js/jquery.fancybox.js"></script>
<script src="/static/js/js/jquery.mixitup.min.js"></script>
<script src="/static/js/js/functions.js" type="text/javascript"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
      {% if messages %}
      {% for a in messages %}
Swal.fire({
  icon: '{{micon}}',
  title: '{{mtitle}}',
  text: '{{a}}',
  {% if not User.is_authenticated %}
  footer: '<a href="">Why do I have this issue?</a>'
  {% endif %}
})
{% endfor %}
{% endif %}
    </script>

</body>
</html>

repair/templates/profile.html
{% extends 'base.html' %}
{% block css %}
<style>
  .alert_box {
    position: absolute;
    top: 50%;
    margin-top: 60px;
    left: 50%;
    transform: translate(-50%, -50%);
  }
  .background {
    position: absolute;
    height: 100%;
    width: 100%;
    top: 0;
    left: 0;
    background: rgba(0, 0, 0, 0.5);
    opacity: 0;
    pointer-events: none;
    transition: all 0.3s ease;
  }
  .alert_box {
    padding: 30px;
    display: flex;
    background: #fff;
    flex-direction: column;
    align-items: center;
    text-align: center;
    max-width: 450px;
    width: 100%;
    border-radius: 5px;
    z-index: 5;
    opacity: 0;
    pointer-events: none;
    transform: translate(-50%, -50%) scale(0.97);
    transition: all 0.3s ease;
  }
  #check:checked ~ .alert_box {
    opacity: 1;
    pointer-events: auto;
    transform: translate(-50%, -50%) scale(1);
  }
  #check:checked ~ .background {
    opacity: 1;
    pointer-events: auto;
  }
  #check {
    display: none;
  }
  .alert_box .icon {
    height: 100px;
    width: 100px;
    color: #f23b26;
    border: 3px solid #f23b26;
    border-radius: 50%;
    line-height: 97px;
    font-size: 50px;
  }
  .alert_box .header2 {
    font-size: 35px;
    font-weight: 500;
    margin: 10px 0;
  }
  .alert_box p {
    font-size: 20px;
  }
  .alert_box .btns {
    margin-top: 20px;
  }
  .btns label {
    display: inline-flex;
    height: 55px;
    padding: 0 30px;
    font-size: 20px;
    font-weight: 400;
    cursor: pointer;
    line-height: 55px;
    outline: none;
    margin: 0 10px;
    border: none;
    color: #fff;
    border-radius: 5px;
    transition: all 0.3s ease;
    background: #2980b9;
  }
  .btns label a {
    text-decoration: none;
  }


  </style>
{% endblock %}
{% block title %} Profile Setting{% endblock %}
{% block name %}Profile{% endblock %}
{% block main %}
<br><br><br><br>

<section id="order-form" class="order_section" style="background: #333;">
    <div class="container order_form padding">
      <div class="row">
        <div class="col-md-12 appointment_form">
          <h2 class="heading">Edit Profile</h2>
          <hr class="heading_space">
        <div class="row">  
         <div class="col-md-8">
         <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
              <div class="row">
              <div class="form-group col-md-12">
              <div id="result" class="text-center"></div></div></div>
               <div class="row">
               <div class="form-group col-md-12">
              <p>Edit your personal data and information</p>
              </div></div>
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="" style="color: #fff;">First Name</label>
                      <input type="text" class="form-control" placeholder="Name" value="{{pp.user.first_name}}"  name="one" id="name"  >
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="" style="color: #fff;">Last Name</label>
                        <input type="text" class="form-control" placeholder="Name" value="{{pp.user.last_name}}"  name="two" id="name"  >
                      </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="" style="color: #fff;">Username</label>
                      <input type="text" class="form-control" placeholder="Name" value="{{pp.user.username}}"  name="three" id="name" >
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="" style="color: #fff;">Email</label>
                        <input type="email" class="form-control" placeholder="Name" value="{{pp.user.email}}"  name="four" id="name" >
                      </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="" style="color: #fff;">Password</label>
                      <input type="password" class="form-control" placeholder="Password"  name="five" id="four"  >
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="" style="color: #fff;">Confirm Password</label>
                        <input type="password" class="form-control" placeholder="Confirm Password"  name="six" id="name"  >
                      </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="" style="color: #fff;">Phone Number</label>
                      <input type="text" class="form-control" placeholder="Name" value="{{pp.phone}}"  name="seven" id="name"  >
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                        <label for="" style="color: #fff;">Profile Pic</label>
                        <input type="file" disabled disabled class="form-control" placeholder="Name"   name="eight" id="name" >
                      </div>
                  </div>
                    <div class="form-group">
                       <div class="btn-submit btn-common-white">
                      <input type="submit" value="Update" id="btn_order_submit" />
                      </div>
                      <a href="{% url 'repair:logout' %}" style="padding: 10px;border-radius: 10px; width: 100px;background-color: red;color: #fff;">logout</a>
                      {% if pp.is_manager == True %}
                      <a href="{% url 'repair:admin' %}" style="padding: 10px;border-radius: 10px; width: 100px;background-color: red;color: #fff;">Admin page</a>
                        {% endif %}
                        </div>
                    </div>
                  </div>
                </div>
         </form>
         <label
                          for="check"
                          style="padding: 10px; border-radius: 20px;width:100px; position: fixed;bottom:30px;right:30px;background-color: red;text-align: center;color:#fff;"
                          >History</label
                        >
         <div class="btn-submit btn-common-white">
          <div class="container">
            <input type="checkbox" id="check" />
            <div class="background"></div>
            <div class="alert_box">
              <div class="icon">
                <i class="fas fa-file"></i>
              </div><br><br>
              {% if history %}
              {% for h in history %}
              <p style="color: #333;">- at {{h.date}} you ordered {{h.device}} {{h.model}} problem.</p><br><br>
              {% endfor %}
              {% else %}
              <p style="color: #333;">- no order history yet.</p><br><br>
              {% endif %}
              <div class="btns">
                <label for="check"> Cancel</label>
              </div>
            </div>
          </div>
             </div> 
        </div>
        </div>
        <div class="col-md-3">
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>
</section>

{% endblock %}