amharic/urls.py
from django.urls import path,re_path
from . import views

app_name = 'amharic'
urlpatterns = [
    path("",views.index,name="amharic"),
    path("about/",views.about,name="a_about"),
    path("faq/",views.faq,name="a_faq"),
]

ludis/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from amharic import views
from django.contrib.sitemaps.views import sitemap
from repair.sitemaps import StaticSitemap
from django.views.generic.base import TemplateView

sitemaps = {
    'posts':StaticSitemap
}

admin.site.name = "Ludis"
admin.site.site_header = "Ludis Administration"

urlpatterns = [
    path('admin-ludis/', admin.site.urls),
    path('',include(('repair.urls','repair'),namespace='repair')),
    path('amh/',include('amharic.urls')),
    path(
        'sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'
        ),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^ads\.txt$', views.googleadsense, name='google_adsense'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

repair/urls.py
from django.urls import path
from . import views

app_name = 'repair'

urlpatterns = [
    path("",views.index,name="index"),
    path("about/",views.about,name="about"),
    path("faq/",views.faq,name="faq"),
    path("login/",views.login_user,name="login"),
    path("terms/",views.terms,name="terms"),
    path("blog/",views.blog,name="blog"),
    path('category/<int:id>/', views.category, name='category'),
    path('category/blog-post/<int:id>/', views.post, name='post'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.custom_logout, name='logout'),
    path('admin-page/',views.admin_page, name='admin'),
    path('admin-page/about-edit',views.about_edit, name='about_edit'),
    path('admin-page/faq-edit',views.sup_edit, name='faq_edit'),
    path('admin-page/user-edit',views.user_edit, name='user_edit'),
    path('admin-page/order',views.book, name='book'),
    path('admin-page/apply',views.com, name='apply'),
    path('admin-page/new',views.new, name='new'),
    path('admin-page/blog/post',views.blogpost, name='blogpost'),
    path('admin-page/setting',views.setting, name='setting'),
    path('admin-page/blog/category',views.cat_edit, name='cat_edit'),
    path('admin-page/profile',views.admin_profile,name='admin_profile'),
    path('register/',views.register_user,name='register'),
    path('register/personal-data/',views.register_user2,name='register2'),
    path('admin-page/brand',views.brand,name='brand'),
    path('admin-page/model/<int:id>/',views.model,name='model'),
    path('admin-page/model/',views.model2,name='modelm'),
    path('admin-page/model/add/',views.modeladd,name='modeladd'),
    path('admin-page/problem/',views.problem2,name='problemm'),
    path('admin-page/problem/<int:id>/',views.problem,name='problem'),
    path('admin-page/problem/add/',views.problemadd,name='problemadd'),
    path('admin-page/price',views.price2,name='pricem'),
    path('admin-page/price/<int:id>/',views.price,name='price'),
    path('admin-page/price/add/',views.priceadd,name='priceadd'),
]

amharic/models.py
from django.db import models

# Create your models here.

amharic/views.py
from django.shortcuts import render,redirect
from repair.models import *
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.http import HttpResponse

# Create your views here.
def index(request):
    User = request.user
    brand = Brand.objects.all()
    amount = Price.objects.all()
    if User.is_authenticated:
        pp = Profile.objects.get(user=User.id)
    else:
        pp = ""
    if request.method == 'POST':
        try:
            if 'no' in request.POST:
                a=request.POST['name']
                b=request.POST['email']
                c=request.POST['phone']
                d=request.POST['country']
                e=request.POST['city']
                f=request.POST['device']
                g=request.POST['model']
                h=request.POST['problem']
                i=request.POST['other']
                model=Order.objects.create(
                    name=a,
                    email=b,
                    device=f,
                    model=g,
                    problems=h,
                    others=i,
                    phone=c,
                    country=d,
                    city=e,
                    my_place=False,
                )
                if not User.is_authenticated:
                    messages.add_message(request, messages.INFO, 'Your order Placed succesfully Login with your account to become customer')
                else:
                    messages.add_message(request, messages.INFO, 'Your order Placed succesfully')
                return redirect('repair:amharic')
            if 'yes' in request.POST:
                a=request.POST['name']
                b=request.POST['email']
                c=request.POST['phone']
                d=request.POST['country']
                e=request.POST['city']
                f=request.POST['device']
                g=request.POST['model']
                h=request.POST['problem']
                i=request.POST['other']
                model=Order.objects.create(
                    name=a,
                    email=b,
                    device=f,
                    model=g,
                    problems=h,
                    others=i,
                    phone=c,
                    country=d,
                    city=e,
                    my_place=True,
                )
                if not User.is_authenticated:
                    messages.add_message(request, messages.INFO, 'Your order Placed succesfully Login with your account to become customer')
                else:
                    messages.add_message(request, messages.INFO, 'Your order Placed succesfully')
                return redirect('repair:amharic')
            if 'apply' in request.POST:
                a = request.POST['name']
                b= request.POST['email']
                c = request.POST['phone']
                d = request.FILES['file']
                main = Apply.objects.create(
                    name=a,
                    email=b,
                    file=d,
                    phone=c,
                )
                if not User.is_authenticated:
                    messages.add_message(request, messages.INFO, 'Your personal data submitted successfully stay tuned Login with your account to become customer')
                else:
                    messages.add_message(request, messages.INFO, 'Your personal data submitted successfully stay tuned')
                return redirect('repair:amharic')
        except:pass
    web = Webpack.objects.get(id=1)
    context = {
        'User':User,
        'web': web,
        'pp':pp,
        'brand':brand,
        'amount':amount,
    }
    return render(request,"a-index.html",context)

def about(request):
    web = Webpack.objects.get(id=1)
    ab = About.objects.all()
    User = request.user
    if User.is_authenticated:
        pp = Profile.objects.get(user=User.id)
    else:
        pp = ""
    context = {
        'web':web,
        'ab':ab,
        'User':User,
        'pp':pp
    }
    return render(request,"a-about.html",context)


def faq(request):
    web = Webpack.objects.get(id=1)
    ab = Faq.objects.all()
    User = request.user
    if User.is_authenticated:
        pp = Profile.objects.get(user=User.id)
    else:
        pp = ""
    context = {
        'web':web,
        'ab':ab,
        'User':User,
        'pp':pp,
    }
    return render(request,"a-faq.html",context)

def googleadsense(request):
    return HttpResponse('google.com, pub-6510615875274346, DIRECT, f08c47fec0942fa0')

amharic/templates/a-about.html
{% extends 'a-base.html' %}
{% block title %}ስለ እኛ{% endblock %}
{% block name %}ስለ እኛ{% endblock %}
{% block main %}
<section id="overview" class="padding-top">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
         <h2 class="heading">ማን ነን?</h2>
         <hr class="heading_space">
         <p>
            አገልግሎቶቻችንን ለሀገር ውስጥ ደንበኞቻችን እናቀርባለን ፣BILIHCARE ልዩ በሆነው አገልግሎቶቹ ውስጥ ያለ ክፍተቶች ሁሉ ልዩ ፍላጎቶችዎ በባለሙያዎች እጅ ላይ ይደርሳሉ። በኢንጂነሮች ፣በመሳሪያዎች እና ሂደቶች ላይ ያለን ትልቅ መዋዕለ ንዋይ ማፍሰስ እና ስለሆነም በእርግጠኝነት እጅግ በጣም ጥሩውን ተሞክሮ ይሰጥዎታል።
         </p>
      </div>
    </div>
  </div>
</section>
<section id="overview" class="padding-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
           <h2 class="heading">እኛ እምንሰራው?</h2>
           <hr class="heading_space">
           <p>
            የእኛ እያንዳንዱ ደንበኛ ከዕውቀታችን፣ ተቃራኒ ዋጋዎች፣ ፈጣን ለውጥ እና የተዋጣለት አገልግሎት ሁሉንም ያካተተ እውቀት በዚህ ልዩ መስክ ምርጡን ይጠቀማል። ምርቶችዎን ከዋናው ጋር ለመመርመር እና ለመጠገን የሚያስችለንን የቅርብ ጊዜ ልዩ አቅርቦቶችን አሟልተናል። በስራችን ውስጥ ያለውን ጥንካሬ እና አስማት በእጃችን ውስጥ ታያለህ.
        </p>
        </div>
      </div>
    </div>
  </section>
  <section id="overview" class="padding-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
           <h2 class="heading">አገልግሎቶች</h2>
           <hr class="heading_space">
           <p>
            ፈጣን የአገልግሎት ሂደት በሞባይል ማእከል እንሰጣለን። ቢሊህኬር በኢትዮጵያ ካሉ ምርጥ ምክንያታዊ የሞባይል አገልግሎት መስጫ ማዕከላት አንዱ ይሆናል፣ ሁሉንም ሞዴሎች ስማርት ፎኖች፣ ላፕቶፕ ቲቪዎች እና ሌሎች የኤሌክትሮኒክስ መግብሮችን እያስተካከልን ነው። አገልግሎታችን የንክኪ ስክሪን መጠገን/መተካት ፣ፈሳሽ እና የውሃ ጉዳት መጠገን ፣የተበላሸ እና የአካል ጉዳት ጥገና ፣የዋናው ሰሌዳ ቺፕ ደረጃ መጠገን ፣ቻርጅ ወደብ ፣የኃይል ቁልፍ ፣የጎን ቁልፍ ፣ካሜራ ጥገና ፣የጆሮ ማዳመጫ መሰኪያ ፣ዋይፋይ ፣ብሉቱዝ ፣ባትሪ መተካት ፣መክፈቻ የተቆለፉ ስልክ እና ፒሲዎች፣ የሶፍትዌር መላ ፍለጋ እና ደረጃ ማሻሻል።
        </p>
        </div>
      </div>
    </div>
  </section>
  <section id="overview" class="padding-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
           <h2 class="heading">ቢሊህኬር የኢትዮጵያ ቁጥር 1 የተደራጀ የሞባይል ስልክ መጠገኛ ማዕከል ይሆናል።</h2>
           <hr class="heading_space">
           <p>
            ቢሊህኬር በኢትዮጵያ ትልቁን የሞባይል ስልክ መጠገኛ ሰንሰለት እየሰራ ሲሆን ትልቁ የኤሌክትሮኒክስ አገልግሎት ሰጪ ይሆናል። እኛ አንድሮይድ እና አይኦኤስ ስማርትፎኖች፣ እና ዊንዶውስ ላይ የተመሰረቱ ላፕቶፖች እንዲሁም ቴሌቪዥኖች መጠገን ጋር ለተያያዙ ሁሉም ፍላጎቶች አንድ ጊዜ መፍትሄ ነን። ኩባንያው በጥገና ኢንዱስትሪ ውስጥ ያሉትን ችግሮች ለመፍታት ያለመ ነው. ቢሊህኬር አፕል፣ አይፎን፣ ቴክኖ፣ ኢቴል፣ ኢንፊኒክስ፣ የሁዋዌ፣ ሌኖቮ፣ ዜድቲኢ፣ ሁሉም የሳምሰንግ እና የሪልሜ ስልኮችን ጨምሮ ለሁሉም ዋና ዋና ብራንዶች ለስማርት ስልኮች፣ ሞባይል እና ላፕቶፖች ጥገና እና አገልግሎት ይሰጣል። ቢሊህኬር በአሁኑ ጊዜ በመላው ኢትዮጵያ ከ3 በላይ የጥገና ሱቆች እና የአገልግሎት መስጫ ሱቆች ያሉት ሲሆን ቁጥሩም በፍጥነት እየጨመረ ነው።
        </p>
        <p>
            እንደ ኦንላይን የሞባይል ጥገና ፣የበር ሞባይል ጥገና ሰፊ የሞባይል ስልክ አገልግሎቶችን እናቀርባለን። ስማርት ፎን እና ላፕቶፕ ካለህ፣ ደህና፣ የዛሬውን አለም ግምት ውስጥ በማስገባት እርግጠኛ ነህ፣ ከዚያ በትክክለኛው ቦታ ላይ ደርሰሃል! Bilihcare ስልክ ወይም ላፕቶፕ መጠገን የሕይወታቸው አስከፊ ቅዠት ሊሆን ይችላል ብለው በማሰብ ቀላል፣ ውጤታማ፣ ቀልጣፋ እና ለሁሉም ሟች ሰዎች ተደራሽ በማድረግ 'ማስተካከል' የሚለውን ቃል እንደገና ይገልፃል።
        </p>
        <p>
            በቢሊህኬር በመላው ኢትዮጵያ የሚገኙ ደንበኞቻችንን በሞባይል ጥገና ዘርፍ በተሻለ በተመጣጣኝ ዋጋ እናገለግላለን። ጥራት ያለው የስማርትፎን ጥገናን 100% የደንበኛ እርካታ እናቀርባለን። የኛ በር የሞባይል መጠገኛ መደብሮች ጎንደር፣ ባህርዳር፣ አዲስ አበባን ጨምሮ በመላው ኢትዮጵያ ይገኛሉ እና ከሁሉም ዋና ዋና ከተሞች በፍጥነት እናቀርባለን።
        </p>
        </div>
      </div>
    </div>
  </section>
  <section id="overview" class="padding-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
           <h2 class="heading">እኛ ሁሌም ችሎታ ፍለጋ ላይ ነን!</h2>
           <hr class="heading_space">
           <p>
            ለአዲስ ንግድ መንገድ መሄድ ቀላል አይደለም። ግን ከትልቅ ኩባንያ ሀብቶች ጋር ሥራ ፈጣሪ የመሆን ሁሉንም ጥቅሞች ቢያገኙስ? ፍራንቻይዝ መክፈት ለእርስዎ ትክክለኛ መንገድ ሊሆን ይችላል። BILIHCARE ቅርንጫፍ እንዲወጡ እና እንዲያሳድጉ ይፈቅድልዎታል ፣እሱም ንግዶቻችንን በትልቁ ኩባንያ እርዳታ እና ድጋፍ እንዲያካሂዱ እድል ይሰጥዎታል ለስኬት የተረጋገጠ ቀመር ስላለን። እርግጥ ነው፣ ብዙ ለሚሹ የንግድ ሥራ ባለቤቶች፣ ፍራንቻይዝ ማድረግ በጣም ያነሰ አደገኛ፣ ግን አሁንም የሚክስ፣ አማራጭ ነው።
        </p>
        </div>
      </div>
    </div>
  </section>
  <section id="overview" class="padding-top">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
           <h2 class="heading">በአጠቃላይ</h2>
           <hr class="heading_space">
           <p>
            ችግሩ ምንም ይሁን ምን, እናስተካክለዋለን. የኛ ቢሊህኬር መሐንዲሶች የሚወዱትን ኤሌክትሮኒክስ ምርጡን ማግኘት እንዲችሉ ይመረምራሉ፣ ያድሱ እና ይጠግኑ

            የኛ የቢሊህኬር መሐንዲሶች የምርት ማሳያ ይሰጡዎታል፣መገጣጠም እንዲለማመዱ እና በኤሌክትሮኒክስዎ የበለጠ እንዲሰሩ የሚያስችልዎትን ጠቃሚ ምክሮችን ያካፍሉ።
            
            Bilihcare ኤሌክትሮኒክስዎን እንደ አዲስ በሚያቆዩ የጥገና አገልግሎቶች ከሁሉም መሳሪያዎችዎ እና መጠቀሚያዎችዎ ያልተቋረጠ አገልግሎት እንደሚያገኙ ያረጋግጣል።
        </p>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

amharic/templates/a-base.html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{web.name}} | {% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="/static/css/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/bistro-icons.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/settings.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/owl.carousel.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/owl.transitions.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/jquery.fancybox.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/zerogrid.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/css/loader.css">
<link rel="shortcut icon" href="{{web.icon.url}}">
<link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    />
<style>
  .alertt {
    margin-top: 30px;
padding: 20px;
background-color: rgb(0, 255, 55); /* Red */
color: rgb(0, 0, 0);
margin-bottom: 15px;
}

/* The close button */
.alertt .closebtn {
margin-left: 15px;
color: rgb(0, 0, 0);
font-weight: bold;
float: right;
font-size: 22px;
line-height: 20px;
cursor: pointer;
transition: 0.3s;
}

/* When moving the mouse over the close button */
.alertt .closebtn:hover {
color: black;
}
</style>
{% block css %}{% endblock %}
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->


</head>

<body>

<!--Loader-->
<div class="loader"> 
   <div class="cssload-container">
     <div class="cssload-circle"></div>
     <div class="cssload-circle"></div>
   </div>
</div>
<!--Topbar-->
<div class="topbar">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p class="pull-left hidden-xs">ብልህኬር, እናንተ ስበሩ እኛ እንጠግናለን!</p>
        <p class="pull-right"><i class="fa fa-phone"></i>አሁን ያነጋግሩ  {{web.phone}}</p>
      </div>
    </div>
  </div>
</div>

<!--Header-->
<header id="main-navigation">
  <div id="navigation" data-spy="affix" data-offset-top="20">
    <div class="container">
      <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-default">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#fixed-collapse-navbar" aria-expanded="false"> 
            <span class="icon-bar top-bar"></span> <span class="icon-bar middle-bar"></span> <span class="icon-bar bottom-bar"></span> 
            </button>
           <a class="navbar-brand"  href="{% url 'amharic:amharic' %}"><img src="/static/images/logo.png" style="background: #333;padding: 10px;border-radius: 20px; width:200px;" alt="logo" class="img-responsive"></a> 
         </div>
        
            <div id="fixed-collapse-navbar" class="navbar-collapse collapse navbar-right">
              <ul class="nav navbar-nav">
                <li>
                   <a href="{% url 'amharic:amharic'%}">ዋና</a>
                   
                </li>
                <li><a href="{% url 'repair:blog' %}">ብሎግ</a></li>
                
                
                    <li><a href="{% url 'amharic:a_about'%}">ስለ እኛ</a></li>
                    <li><a href="{% url 'amharic:a_faq' %}">FAQ</a></li>
                  
                    {% if User.is_authenticated %}
                    {% if pp.profile_pic %}
          <li><a href="{% url 'repair:profile' %}"><img  style="width: 50px;border-radius: 50%;height: 50px;" src="{{pp.profile_pic.url}}" alt=""></a></li>
          {% else %}
          <li><a href="{% url 'repair:profile' %}"><img  style="width: 50px;border-radius: 50%;height: 50px;" src="/static/images/undraw_pic_profile_re_7g2h.svg" alt=""></a></li>
          {% endif %}
                    {% else %}
                    <li><a href="{% url 'repair:login' %}">ግባ</a></li>
                    {% endif %}
                    <a href="{% url 'repair:index' %}">
                      <img  style="width: 30px;margin-top: 10px;border-radius: 50%;height: 30px;" src="/static/images/usaa.png" alt="">
                    </a>
              </ul>
            </div>
         </nav>
         </div>
       </div>
     </div>
  </div>
</header>

<!--Page header & Title-->
<section id="page_header">
<div class="page_title">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
         <h2 class="title">{% block name %}{% endblock %}</h2>
         <p></p>
      </div>
    </div>
  </div>
</div>  
</section>
{% block main %}

{% endblock %}

<!--Footer-->
<footer class="padding-top bg_black" style="margin-top: 200px;">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6 footer_column">
        <h4 class="heading">ለምን እኛ</h4>
        <hr class="half_space">
        <p class="half_space">አገልግሎቶቻችንን ለሀገር ውስጥ ደንበኞቻችን እናቀርባለን ፣BILIHCARE ያለምንም ክፍተቶች በአገልግሎቶቹ ላይ ልዩ ያደርገዋል። የእኛ መጠነ ሰፊ ኢንቨስትመንቶች በኢንጂነሮች ፣ መሳሪያዎች እና ሂደቶች እና በውጤቱም እጅግ በጣም ጥሩውን ተሞክሮ ይሰጥዎታል።</p>
      </div>
      <div class="col-md-3 col-sm-6 footer_column">
        <h4 class="heading">Quick Links</h4>
        <hr class="half_space">
        <ul class="widget_links">
          <li><a href="{% url 'amharic:amharic' %}">ዋና</a></li>
          <li><a href="{% url 'repair:blog' %}">ብሎግ</a></li>
          <li><a href="{% url 'amharic:a_faq' %}">FAQ</a></li>
          <li><a href="{% url 'repair:terms' %}">Terms </a></li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-6 footer_column">
        <h4 class="heading">ተገናኝ</h4>
        <hr class="half_space">
        <p>BILIHCARE, እናንተ ስበሩ እኛ እንጠግናለን</p>
        <p class="address"><i class="icon-location"></i>{{web.address}}</p>
        <p class="address"><i class="fa fa-phone"></i>{{web.phone}}</p>
        <p class="address"><i class="icon-dollar"></i><a href="mailto:{{web.email}}">{{web.email}}</a></p>
      </div>  
    </div>
    <div class="row">
      <div class="col-md-12">
         <div class="copyright clearfix">
           <ul class="social_icon">
        {% if web.facebook %}
        <li><a href="{{web.facebook}}" class="facebook"><i class="fab fa-facebook-f"></i></a></li>
        {% endif %}
        {% if web.telegram %}
        <li><a href="{{web.telegram}}" class="twitter"><i class="fa fa-telegram"></i></a></li>
        {% endif %}
        {% if web.instagram %}
        <li><a href="{{web.instagram}}" class="twitter"><i class="fab fa-instagram"></i></a></li>
        {% endif %}
        {% if web.youtube %}
        <li><a href="{{web.youtube}}" class="twitter"><i class="fab fa-youtube"></i></a></li>
        {% endif %}
        {% if web.tiktok %}
        <li><a href="{{web.tiktok}}" class="twitter"><i class="fab fa-tiktok"></i></a></li>
        {% endif %}
        {% if web.email %}
        <li><a href="mailto:{{web.email}}" class="twitter"><i class="fa fa-envelope"></i></a></li>
        {% endif %}
        {% if web.twitter %}
        <li><a href="{{web.twitter}}" class="twitter"><i class="icon-twitter"></i></a></li>
        {% endif %}
               </ul>
         </div>
       </div>
     </div>
  </div>
</footer>
<a href="#" id="back-top"><i class="fa fa-angle-up fa-2x"></i></a>
{% block script %}

{% endblock %}
<script src="/static/js/js/jquery-2.2.3.js" type="text/javascript"></script>
<script src="/static/js/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/js/js/jquery.parallax-1.1.3.js"></script>
<script src="/static/js/js/jquery.appear.js"></script>  
<script src="/static/js/js/jquery-countTo.js"></script>
<script src="/static/js/js/owl.carousel.min.js" type="text/javascript"></script>
<script src="/static/js/js/jquery.fancybox.js"></script>
<script src="/static/js/js/jquery.mixitup.min.js"></script>
<script src="/static/js/js/functions.js" type="text/javascript"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
      {% if messages %}
      {% for a in messages %}
Swal.fire({
  icon: '{{micon}}',
  title: '{{mtitle}}',
  text: '{{a}}',
  {% if not User.is_authenticated %}
  footer: '<a href="">Why do I have this issue?</a>'
  {% endif %}
})
{% endfor %}
{% endif %}
    </script>

</body>
</html>