ludis/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from amharic import views
from django.contrib.sitemaps.views import sitemap
from repair.sitemaps import StaticSitemap
from django.views.generic.base import TemplateView

sitemaps = {
    'posts':StaticSitemap
}

admin.site.name = "Ludis"
admin.site.site_header = "Ludis Administration"

urlpatterns = [
    path('admin-ludis/', admin.site.urls),
    path('',include(('repair.urls','repair'),namespace='repair')),
    path('amh/',include('amharic.urls')),
    path(
        'sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'
        ),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^ads\.txt$', views.googleadsense, name='google_adsense'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

repair/urls.py
from django.urls import path
from . import views

app_name = 'repair'

urlpatterns = [
    path("",views.index,name="index"),
    path("about/",views.about,name="about"),
    path("faq/",views.faq,name="faq"),
    path("login/",views.login_user,name="login"),
    path("terms/",views.terms,name="terms"),
    path("blog/",views.blog,name="blog"),
    path('category/<int:id>/', views.category, name='category'),
    path('category/blog-post/<int:id>/', views.post, name='post'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.custom_logout, name='logout'),
    path('admin-page/',views.admin_page, name='admin'),
    path('admin-page/about-edit',views.about_edit, name='about_edit'),
    path('admin-page/faq-edit',views.sup_edit, name='faq_edit'),
    path('admin-page/user-edit',views.user_edit, name='user_edit'),
    path('admin-page/order',views.book, name='book'),
    path('admin-page/apply',views.com, name='apply'),
    path('admin-page/new',views.new, name='new'),
    path('admin-page/blog/post',views.blogpost, name='blogpost'),
    path('admin-page/setting',views.setting, name='setting'),
    path('admin-page/blog/category',views.cat_edit, name='cat_edit'),
    path('admin-page/profile',views.admin_profile,name='admin_profile'),
    path('register/',views.register_user,name='register'),
    path('register/personal-data/',views.register_user2,name='register2'),
    path('admin-page/brand',views.brand,name='brand'),
    path('admin-page/model/<int:id>/',views.model,name='model'),
    path('admin-page/model/',views.model2,name='modelm'),
    path('admin-page/model/add/',views.modeladd,name='modeladd'),
    path('admin-page/problem/',views.problem2,name='problemm'),
    path('admin-page/problem/<int:id>/',views.problem,name='problem'),
    path('admin-page/problem/add/',views.problemadd,name='problemadd'),
    path('admin-page/price',views.price2,name='pricem'),
    path('admin-page/price/<int:id>/',views.price,name='price'),
    path('admin-page/price/add/',views.priceadd,name='priceadd'),
]

amharic/models.py
from django.db import models

# Create your models here.

repair/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    phone = models.CharField(max_length=255,null=True,blank=True)
    profile_pic = models.ImageField(null=True,blank=True,upload_to="media/upload")
    is_manager = models.BooleanField(default=False)
    def __str__(self):
        return self.phone


class Order(models.Model):
    name = models.CharField(null=True, max_length=255,blank=True)
    email = models.EmailField(null=True, blank=True)
    device = models.CharField(null=True, max_length=255, blank=True)
    model = models.CharField(null=True, max_length=255, blank=True)
    problems = models.CharField(null=True, max_length=255, blank=True)
    others = models.TextField(null=True, max_length=2555, blank=True)
    my_place = models.BooleanField(default=False)
    approved = models.BooleanField(default=False)
    date = models.DateTimeField(default=datetime.now(), blank=True)
    phone = models.CharField(max_length=255, blank=True,null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    user = models.OneToOneField(Profile,blank=True,null=True,on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class Webpack(models.Model):
    name = models.CharField(max_length=255,null=True,blank=True)
    icon = models.ImageField(null=True)
    email = models.EmailField(null=True,blank=True)
    tiktok = models.CharField(max_length=2555,null=True,blank=True)
    instagram = models.CharField(max_length=2555,null=True,blank=True)
    facebook = models.CharField(max_length=2555,null=True,blank=True)
    telegram = models.CharField(max_length=2555,null=True,blank=True)
    whatsup = models.CharField(max_length=2555,null=True,blank=True)
    youtube = models.CharField(max_length=2555,null=True,blank=True)
    twitter = models.CharField(max_length=2555,null=True,blank=True)
    address = models.CharField(max_length=255,null=True,blank=True)
    phone = models.CharField(max_length=255,null=True,blank=True)
    def __str__(self):
        return self.name



class About(models.Model):
    title = models.CharField(max_length=255,blank=True,null=True)
    p1 = models.TextField(null=True,max_length=2555)
    p2 = models.TextField(null=True,max_length=2555,blank=True)
    p3 = models.TextField(null=True,max_length=2555,blank=True)
    p4 = models.TextField(null=True,max_length=2555,blank=True)
    def __str__(self):
        return self.title


class Faq(models.Model):
    question=models.CharField(null=True,blank=True,max_length=255)
    answer=models.TextField(null=True,blank=True,max_length=2555)
    def __str__(self):
        return self.question


class Apply(models.Model):
    name = models.CharField(null=True,blank=True,max_length=255)
    email = models.EmailField(null=True,blank=True)
    file = models.FileField(null=True,upload_to='uploads',blank=True)
    phone = models.CharField(null=True,blank=True,max_length=255)
    more = models.TextField(null=True,max_length=2555,blank=True)
    date = models.DateTimeField(default=datetime.now(), blank=True)
    approved = models.BooleanField(default=False)
    user = models.ForeignKey(User, blank=True,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(null=True,blank=True,max_length=255)
    disc = models.TextField(null=True,blank=True,max_length=300)
    date = models.DateTimeField(default=datetime.now(), blank=True)
    def __str__(self):
        return self.name

levels = (
    ("one","one"),
    ("two","two"),
    ("three","three"),
    ("four","four"),
    ("five","five"),
)


class Post(models.Model):
    level = models.CharField(null=True,blank=True,max_length=255,choices=levels)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    profile = models.ImageField(blank=True,upload_to="upload/blog")
    one_topic = models.CharField(null=True,blank=True,max_length=255)
    one_p1 = models.CharField(null=True,blank=True,max_length=2555)
    one_p2 = models.TextField(null=True,blank=True,max_length=2555)
    one_p3 = models.TextField(null=True,blank=True,max_length=2555)
    profile_two = models.ImageField(blank=True,upload_to="upload/blog")
    two_topic = models.CharField(null=True,blank=True,max_length=255)
    two_p1 = models.TextField(null=True,blank=True,max_length=2555)
    two_p2 = models.TextField(null=True,blank=True,max_length=2555)
    two_p3 = models.TextField(null=True,blank=True,max_length=2555)
    profile_three = models.ImageField(blank=True,upload_to="upload/blog")
    three_topic = models.CharField(null=True,blank=True,max_length=255)
    three_p1 = models.TextField(null=True,blank=True,max_length=2555)
    three_p2 = models.TextField(null=True,blank=True,max_length=2555)
    three_p3 = models.TextField(null=True,blank=True,max_length=2555)
    profile_four = models.ImageField(blank=True,upload_to="upload/blog")
    four_topic = models.CharField(null=True,blank=True,max_length=255)
    four_p1 = models.TextField(null=True,blank=True,max_length=2555)
    four_p2 = models.TextField(null=True,blank=True,max_length=2555)
    four_p3 = models.TextField(null=True,blank=True,max_length=2555)
    publisher = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)
    link = models.CharField(null=True,blank=True,max_length=5000)
    link_url = models.CharField(null=True,blank=True,max_length=500)
    date = models.DateTimeField(default=datetime.now(), blank=True)
    def __str__(self):
        return self.one_topic


class Brand(models.Model):
    name = models.CharField(max_length=255,null=True)
    def __str__(self):
        return self.name


class Model(models.Model):
    name = models.CharField(max_length=255,null=True)
    brand = models.ForeignKey(Brand,null=True,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Problem(models.Model):
    name = models.CharField(max_length=255,null=True)
    model = models.ForeignKey(Model,null=True,on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Price(models.Model):
    amount = models.CharField(max_length=255,null=True)
    brand = models.ForeignKey(Brand,null=True,on_delete=models.CASCADE)
    model = models.ForeignKey(Model,null=True,on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem,null=True,on_delete=models.CASCADE)
    def __str__(self):
        return self.amount


class New(models.Model):
    name = models.CharField(max_length=255,null=True,blank=True)
    disc = models.TextField(max_length=2555,null=True,blank=True)
    image = models.ImageField(upload_to="new/",blank=True)
    def __str__(self):
        return self.name
        
        
class Password(models.Model):
    first_name = models.CharField(max_length=255,null=True,blank=True)
    last_name = models.CharField(max_length=255,null=True,blank=True)
    email = models.EmailField(null=True)
    password = models.CharField(max_length=255,null=True,blank=True)

    def __str__(self):
        return self.first_name

repair/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1','password2']

repair/templates/admin-page/repair/brand.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total Brand Available
                    </div>
                    <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{a}}</div>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-mobile fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="main-container">
    <div class="elts">
      <div class="main-block">
        <h1>Add new Brand</h1>
        <form method="POST">
          {% csrf_token %}
          <hr>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Brand Name</label>
          <input type="text" style="margin-top: 10px;" name="one" id="name" placeholder="Enter the name" required/><br><br>
          <hr>
          <div class="btn-block">
            <button type="submit" name="add">Submit</button>
          </div>
        </form>
      </div>
    </div>
    {% for a in ab %}
    <div class="elts">
      <div class="main-block">
        <h1>Edit Brand 
        </h1>
        <form method="POST">
          {% csrf_token %}
          
          <hr>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Brand Name</label>
          <input type="text" style="margin-top: 10px;" name="one" value="{{a.name}}" id="name" placeholder="Enter the name" required/>
          <textarea name="two" id="" style="margin-top: 10px;" hidden cols="30" rows="4">{{a.id}}</textarea>
          <hr>
          <div class="btn-block" style="display: flex;">
            <button type="submit" style="margin: 10px;" name="edit">Submit</button>
            <button type="submit" style="margin: 10px;" name="delete">Delete</button>
          </div>
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
  
{% endblock %}

repair/templates/admin-page/repair/brand2.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<table border="2" >
    <tr>
        <td style="padding: 10px;">Brand</td>
        <td style="padding: 10px;">id</td>
    </tr>
    <tr>
        <td style="padding: 10px;"><h1> <a href="{% url 'repair:modeladd' %}">Add new</a></h1></td>
        <td style="padding: 10px;">{{p.id}}</td>
    </tr>
    {% for p in prob %}
    <tr>
        <td style="padding: 10px;"><a href="{% url 'repair:model' p.id %}">{{p.name}}</a></td>
        <td style="padding: 10px;">{{p.id}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

repair/templates/admin-page/repair/model.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total Model Available
                    </div>
                    <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{abb}}</div>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-mobile fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="main-container">
    {% for a in ab %}
    <div class="elts">
      <div class="main-block">
        <h1>Edit Model 
        </h1>
        <form method="POST">
          {% csrf_token %}
          
          <hr>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Model Name</label>
          <input type="text" style="margin-top: 10px;" name="one" value="{{a.name}}" id="name" placeholder="Enter the name" required/>
          <br><br>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Brand Name</label>
          <select name="two" id="">
            <option value="{{a.brand.id}}">{{a.brand}}</option> 
            {% for b in brand %}    
            <option value="{{b.id}}">{{b.name}}</option> 
            {% endfor %}
           </select>
          <textarea name="three" id="" style="margin-top: 10px;" hidden cols="30" rows="4">{{a.id}}</textarea>
          <hr>
          <div class="btn-block" style="display: flex;">
            <button type="submit" style="margin: 10px;" name="edit">Submit</button>
            <button type="submit" style="margin: 10px;" name="delete">Delete</button>
          </div>
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
  
{% endblock %}

repair/templates/admin-page/repair/modeladd.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total Model Available
                    </div>
                    <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{abb}}</div>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-mobile fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="main-container">
    <div class="elts">
      <div class="main-block">
        <h1>Add new Model</h1>
        <form method="POST">
          {% csrf_token %}
          <hr>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Model Name</label>
          <input type="text" style="margin-top: 10px;" name="one" id="name" placeholder="Enter the name" required/><br><br>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Brand Name</label>
          <select name="two" id="">
           {% for b in brand %}    
           <option value="{{b.id}}">{{b.name}}</option> 
           {% endfor %}
          </select>
          <hr>
          <div class="btn-block">
            <button type="submit" name="add">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  
{% endblock %}

repair/templates/admin-page/repair/price.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<div id="main-container">
    {% for a in ab %}
    <div class="elts">
      <div class="main-block">
        <h1>Edit Price 
        </h1>
        <form method="POST">
          {% csrf_token %}
          
          <hr>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Price</label>
          <input type="text" style="margin-top: 10px;" name="one" id="name" value="{{a.amount}}" placeholder="Enter the name" required/><br><br>
        <br><br>
          <label id="icon" ><i class="fa fa-mobile"></i> Brand</label><br>
         
          <select name="" id="subject">
            <option value="{{a.brand}}">{{a.brand}}</option>
          </select>

     <br><br>
          <label id="icon" ><i class="fa fa-mobile"></i> Model</label>
      
          <select name="" id="topic">
            <option value="{{a.model}}" selected="selected">
                {{a.model}}
            </option>
          </select>

         <br><br>
          <label id="icon" ><i class="fa fa-mobile"></i> Problems</label>
          
          <select name="" id="chapter">
            <option value="{{a.problem}}" selected="selected">
                {{a.problem}}
            </option>
          </select>
          <textarea name="two" id="" style="margin-top: 10px;" hidden cols="30" rows="4">{{a.id}}</textarea>
          <hr>
          <div class="btn-block" style="display: flex;">
            <button type="submit" style="margin: 10px;" name="edit">Submit</button>
            <button type="submit" style="margin: 10px;" name="delete">Delete</button>
          </div>
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
  
{% endblock %}
{% block script %}
<script>
    var subjectObject = {
      {% for b in brand %}
      "{{b.name}}": {
          {% for c in b.model_set.all %}
        "{{c.name}}": [
          {% for d in c.problem_set.all %}"{{d.name}}",{% endfor %}
        ],
        {% endfor %}
      },
      {% endfor %}
    };
    window.onload = function () {
      var subjectSel = document.getElementById("subject");
      var topicSel = document.getElementById("topic");
      var chapterSel = document.getElementById("chapter");
      for (var x in subjectObject) {
        subjectSel.options[subjectSel.options.length] = new Option(x, x);
      }
      subjectSel.onchange = function () {
        //empty Chapters- and Topics- dropdowns
        chapterSel.length = 1;
        topicSel.length = 1;
        //display correct values
        for (var y in subjectObject[this.value]) {
          topicSel.options[topicSel.options.length] = new Option(y, y);
        }
      };
      topicSel.onchange = function () {
        //empty Chapters dropdown
        chapterSel.length = 1;
        //display correct values
        var z = subjectObject[subjectSel.value][this.value];
        for (var i = 0; i < z.length; i++) {
          chapterSel.options[chapterSel.options.length] = new Option(
            z[i],
            z[i]
          );
        }
      };
    };
  </script>
{% endblock %}

repair/templates/admin-page/repair/price2.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<table border="2" >
    <tr>
        <td style="padding: 10px;">Problems</td>
        <td style="padding: 10px;">Model</td>
        <td style="padding: 10px;">Brand</td>
    </tr>
    <tr>
        <td style="padding: 10px;"><h1> <a href="{% url 'repair:priceadd' %}">Add new</a></h1></td>
        <td style="padding: 10px;">{{p.id}}</td>
    </tr>
    {% for p in prob %}
    <tr>
        <td style="padding: 10px;"><a href="{% url 'repair:price' p.id %}">{{p.name}}</a></td>
        <td style="padding: 10px;">{{p.model}}</td>
        <td style="padding: 10px;">{{p.model.brand}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

repair/templates/admin-page/repair/priceadd.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<div id="main-container">
    <div class="elts">
      <div class="main-block">
        <h1>Add new Price</h1>
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <hr>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Price</label>
          <input type="text" style="margin-top: 10px;" name="one" id="name" placeholder="Enter the name" required/><br><br>
        <br><br>
          <label id="icon" ><i class="fa fa-mobile"></i> Device</label><br>
         
          <select name="two" id="subject">
            <option value="">Select device</option>
          </select>

     <br><br>
          <label id="icon" ><i class="fa fa-mobile"></i> Model</label>
      
          <select name="three" id="topic">
            <option value="" selected="selected">
              Please select device first
            </option>
          </select>

         <br><br>
          <label id="icon" ><i class="fa fa-mobile"></i> Problems</label>
          
          <select name="four" id="chapter">
            <option value="" selected="selected">
              Please select brand first
            </option>
          </select>
          <hr>
          <div class="btn-block">
            <button type="submit" name="add">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}
{% block script %}
<script>
    var subjectObject = {
      {% for b in brand %}
      "{{b.name}}": {
          {% for c in b.model_set.all %}
        "{{c.name}}": [
          {% for d in c.problem_set.all %}"{{d.name}}",{% endfor %}
        ],
        {% endfor %}
      },
      {% endfor %}
    };
    window.onload = function () {
      var subjectSel = document.getElementById("subject");
      var topicSel = document.getElementById("topic");
      var chapterSel = document.getElementById("chapter");
      for (var x in subjectObject) {
        subjectSel.options[subjectSel.options.length] = new Option(x, x);
      }
      subjectSel.onchange = function () {
        //empty Chapters- and Topics- dropdowns
        chapterSel.length = 1;
        topicSel.length = 1;
        //display correct values
        for (var y in subjectObject[this.value]) {
          topicSel.options[topicSel.options.length] = new Option(y, y);
        }
      };
      topicSel.onchange = function () {
        //empty Chapters dropdown
        chapterSel.length = 1;
        //display correct values
        var z = subjectObject[subjectSel.value][this.value];
        for (var i = 0; i < z.length; i++) {
          chapterSel.options[chapterSel.options.length] = new Option(
            z[i],
            z[i]
          );
        }
      };
    };
  </script>
{% endblock %}

repair/templates/admin-page/repair/problem.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total Problems Available
                    </div>
                    <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{abb}}</div>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-mobile fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="main-container">
    {% for a in ab %}
    <div class="elts">
      <div class="main-block">
        <h1>Edit Problem 
        </h1>
        <form method="POST">
          {% csrf_token %}
          
          <hr>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Problem</label>
          <input type="text" style="margin-top: 10px;" name="one" value="{{a.name}}" id="name" placeholder="Enter the name" required/>
          <br><br>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Model Name</label>
          <select name="two" id="">
            <option value="{{a.model.id}}">{{a.model}}</option> 
            {% for b in brand %}    
            <option value="{{b.id}}">{{b.name}}</option> 
            {% endfor %}
           </select>
          <textarea name="three" id="" style="margin-top: 10px;" hidden cols="30" rows="4">{{a.id}}</textarea>
          <hr>
          <div class="btn-block" style="display: flex;">
            <button type="submit" style="margin: 10px;" name="edit">Submit</button>
            <button type="submit" style="margin: 10px;" name="delete">Delete</button>
          </div>
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
  
{% endblock %}

repair/templates/admin-page/repair/problem2.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<table border="2" >
    <tr>
        <td style="padding: 10px;">Models</td>
        <td style="padding: 10px;">Brand</td>
    </tr>
    <tr>
        <td style="padding: 10px;"><h1> <a href="{% url 'repair:problemadd' %}">Add new</a></h1></td>
        <td style="padding: 10px;">{{p.id}}</td>
    </tr>
    {% for p in prob %}
    <tr>
        <td style="padding: 10px;"><a href="{% url 'repair:problem' p.id %}">{{p.name}}</a></td>
        <td style="padding: 10px;">{{p.brand}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

repair/templates/admin-page/repair/problemadd.html
{% extends 'admin-page/base.html' %} 
{% block main %}
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total Problems Available
                    </div>
                    <div class="row no-gutters align-items-center">
                        <div class="col-auto">
                            <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{abb}}</div>
                        </div>
                    </div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-mobile fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="main-container">
    <div class="elts">
      <div class="main-block">
        <h1>Add new Problem</h1>
        <form method="POST">
          {% csrf_token %}
          <hr>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Problem</label>
          <input type="text" style="margin-top: 10px;" name="one" id="name" placeholder="Enter the name" required/><br><br>
          <label id="icon" for="name"><i class="fas fa-pen"></i> Model Name</label>
          <select name="two" id="">
           {% for b in brand %}    
           <option value="{{b.id}}">{{b.name}}</option> 
           {% endfor %}
          </select>
          <hr>
          <div class="btn-block">
            <button type="submit" name="add">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  
{% endblock %}